# Generated by Django 5.2.4 on 2025-07-04 12:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('interview', '0002_question_competencies'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='question_id',
        ),
    ]
