# Generated by Django 5.2.4 on 2025-07-04 13:05

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interview', '0004_question_is_active_alter_question_competencies'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='options',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=200), blank=True, help_text='Only for multiple choice questions', null=True, size=None),
        ),
    ]
