# Generated by Django 5.2.4 on 2025-07-10 10:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interview', '0010_candidate_interview_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='cnic',
            field=models.CharField(max_length=254, unique=True),
        ),
        migrations.CreateModel(
            name='CandidateScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('competency_scores', models.JSONField(default=dict)),
                ('total_score', models.FloatField(default=0.0)),
                ('scored_at', models.DateTimeField(auto_now_add=True)),
                ('candidate', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='score', to='interview.candidate')),
            ],
        ),
    ]
