# Generated by Django 5.2.4 on 2025-07-10 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interview', '0011_alter_candidate_cnic_candidatescore'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, unique=True),
        ),
    ]
