# Generated by Django 5.2.4 on 2025-07-10 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interview', '0012_alter_candidate_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='response',
            name='score',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
