# Generated by Django 5.2.4 on 2025-07-11 09:47

import uuid
from django.db import migrations, models


def generate_invite_tokens(apps, schema_editor):
    Candidate = apps.get_model('interview', 'Candidate')
    for candidate in Candidate.objects.all():
        candidate.invite_token = uuid.uuid4()
        candidate.save()


class Migration(migrations.Migration):

    dependencies = [
        ('interview', '0013_response_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='invite_token',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AddField(
            model_name='candidate',
            name='is_invited',
            field=models.BooleanField(default=False),
        ),
        migrations.RunPython(generate_invite_tokens),
    ]
