# Generated by Django 5.2.4 on 2025-07-11 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interview', '0014_candidate_invite_token_candidate_is_invited'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='invite_token',
            field=models.UUIDField(blank=True, editable=False, null=True, unique=True),
        ),
    ]
