# Generated by Django 5.2.4 on 2025-07-12 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interview', '0016_alter_response_candidate_delete_candidatescore_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='follow_up_prompt',
            field=models.CharField(blank=True, help_text="E.g., 'That's insightful! Want to elaborate?'", max_length=255),
        ),
    ]
