# Generated by Django 5.2.4 on 2025-07-04 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interview', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='competencies',
            field=models.CharField(default='Default', max_length=250),
            preserve_default=False,
        ),
    ]
