# Generated by Django 5.2.4 on 2025-07-04 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interview', '0003_remove_question_question_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='competencies',
            field=models.CharField(choices=[('motivation & intent', 'Motivation & Intent'), ('teamwork', 'Teamwork'), ('communication & feedback', 'Communication & Feedback'), ('value & inclusion', 'Value & Inclusion'), ('self-reflection', 'Self-Reflection')], max_length=50),
        ),
    ]
