# Generated by Django 5.2.4 on 2025-07-09 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interview', '0008_candidate_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='cnic',
            field=models.CharField(default='00000-0000000-0', max_length=254),
            preserve_default=False,
        ),
    ]
