# Generated by Django 5.2.4 on 2025-07-12 10:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('candidate_id', models.CharField(max_length=100, unique=True)),
                ('name', models.CharField(blank=True, max_length=100)),
                ('email', models.EmailField(blank=True, max_length=254, null=True, unique=True)),
                ('cnic', models.CharField(max_length=254, unique=True)),
                ('interview_type', models.CharField(choices=[('hr', 'HR Interview'), ('academic', 'Academic Interview')], default='hr', max_length=20)),
                ('status', models.CharField(choices=[('not_started', 'Not Started'), ('in_progress', 'In Progress'), ('completed', 'Completed')], default='not_started', max_length=20)),
                ('invite_token', models.UUIDField(blank=True, editable=False, null=True, unique=True)),
                ('is_invited', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='CandidateScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('competency_scores', models.JSONField(default=dict)),
                ('total_score', models.FloatField(default=0.0)),
                ('scored_at', models.DateTimeField(auto_now_add=True)),
                ('candidate', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='score', to='candidate.candidate')),
            ],
        ),
    ]
